#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Enable underground railways from a spawn location
# to a woodland mansion and an ocean monument
# with ladders from above at stations.
#
# Possible values: true | false
#
underground-railways: true

#
# Increase density according to distance from the map center.
#
# Use 0 to disable the feature.
#

distance-density-multiplier: 5_000