name: RailNet
main: com.gmail.uprial.railnet.RailNet
version: 0.3.1
api-version: 1.14
commands:
  railnet:
    description: RailNet config help
    usage: /railnet help
    permission:
    permission-message:
permissions:
  railnet.repopulate-loaded:
    description: Gives access to RailNet 'repopulate-loaded' command
    default: op
  railnet.claim:
    description: Gives access to RailNet 'claim' command
    default: op
  railnet.break:
    description: Gives access to RailNet 'break' command
    default: op
  railnet.loaded-stats:
    description: Gives access to RailNet 'loaded-stats' command
    default: op
