name: RailNet
main: com.gmail.uprial.railnet.RailNet
version: 0.1.0
api-version: 1.14
commands:
  railnet:
    description: Reload RailNet config
    usage: /railnet help
    permission:
    permission-message:
permissions:
  railnet.reload:
    description: Gives access to RailNet 'reload' command
    default: op
  railnet.repopulate-loaded:
    description: Gives access to RailNet 'repopulate-loaded' command
    default: op
  railnet.claim:
    description: Gives access to RailNet 'claim' command
    default: op
